default:
  image: docker:20.10.22
  services:
    - docker:20.10.22-dind
  tags:
    - privileged
    - amd64

stages:
  - build
  - push-latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_BUILDKIT: 1

  IMAGE_NAME: $CI_REGISTRY_IMAGE
  IMAGE_TAG:  $CI_COMMIT_REF_SLUG
  IMAGE:      $IMAGE_NAME:$IMAGE_TAG

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --pull -t $IMAGE .
    - docker push $IMAGE

push-image-latest:
  stage: push-latest
  script:
    - docker pull $IMAGE
    - docker tag $IMAGE $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:latest
  only:
    - main